In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  os
import seaborn as sns
%matplotlib inline

In [2]:
#Read Data
df = pd.read_csv("Data_cleaning_xz/attributes_of_top_7_collections/cleaned_almost_famous_pandas.csv")
df.head()

,Unnamed: 0,id,price,owner,collectionName,collectionTitle,img,title,propertyCategory,creators,...,Outfit,Head,Glasses,Eyes,Extras,Skin,Mouth,Body,Background,Face
0,0,27gDWHQCryqpfDN7bf1ThQrySWJFJKSEbmFyyximNSak,0.58,BoL3yjzMt5qsCuat8AuuAZi3tD9CkEgTk4Y6KezYVeWP,almost_famous_pandas,Almost Famous Pandas,https://bafybeiemhibfs3qi24mtw2iiuyjwb5bil4syp...,Almost Famous Pandas #6978,image,[{'address': 'A3YoUrpRZNMNvPAS7cpVQtYtF9iW5vdX...,...,None,RedSidewaysCap,FlyEyeGlasses,Regular,None,None,None,Inverted,DarkBlue,None
1,1,7jrvBATdBbDVdqFgCVXyMbGNMLwWFWcL5Mn1hyJJfSwa,0.60,DeBm9DxgZ5X8TECuQdag5RJLvGULeA4HfWhEWp2aed9a,almost_famous_pandas,Almost Famous Pandas,https://bafybeierhvzvpqnvzvemhmklyfii4tbb7r4ry...,Almost Famous Pandas #6481,image,[{'address': 'A3YoUrpRZNMNvPAS7cpVQtYtF9iW5vdX...,...,RedSweaterVest,AfroBandana,None,Regular,None,None,Closed,BlackMonochrome,Green,None
2,2,2wYNkFLm5AixJAWHSk8ZqvJavK5HPMNXi6XYAcAiU5tK,0.60,HWv3PL1fGFxPT5PtzwQXQpdvu48oNoAkRcrezJTuKFJX,almost_famous_pandas,Almost Famous Pandas,https://bafybeiayxkqukq2kshqzeov6k3rfd6jdriufk...,Almost Famous Pandas #7521,image,[{'address': 'A3YoUrpRZNMNvPAS7cpVQtYtF9iW5vdX...,...,WhiteBeaterJeans,RedDomeHat,FlyEyeGlasses,Regular,None,None,None,Base,Pink,None
3,3,4Kw2W3ejGYGF4pBSNxyVeujMU84WauK2vzb9pA84ViCe,0.60,2wvTtheNr5suAWKKLvskZPcriuzaNLUcse8QfFr7mFSK,almost_famous_pandas,Almost Famous Pandas,https://bafybeie5dwrayyqefvmze5ppslbkslvrs2brd...,Almost Famous Pandas #7674,image,[{'address': 'A3YoUrpRZNMNvPAS7cpVQtYtF9iW5vdX...,...,BlackSuspenderSuit,TopHat,None,Regular,None,None,Closed,Base,Green,None
4,4,8rknZJsGVKRpzmNhUBpJhU3FW1ND4weUEPNDm24i9KqQ,0.64,9UNbwFEefFhSZ6A6Udgag6WVQZJTiSgZguwJQG4P7mNi,almost_famous_pandas,Almost Famous Pandas,https://bafybeidk3qb2zalzcysgsounbensddi4lk4e2...,Almost Famous Pandas #961,image,[{'address': 'A3YoUrpRZNMNvPAS7cpVQtYtF9iW5vdX...,...,DoubleBreastedSuit,BlondeCurlyHair,None,Crosses,None,None,Closed,Base,Green,None

In [3]:
df.describe()

        Unnamed: 0           price      version
count  6075.000000     6075.000000  6075.000000
mean   3037.000000      302.020344     2.544198
std    1753.845774    13206.359631     1.100549
min       0.000000        0.180000     1.000000
25%    1518.500000        0.990000     2.000000
50%    3037.000000        1.400000     3.000000
75%    4555.500000        2.500000     4.000000
max    6074.000000  1000000.000000     4.000000

In [4]:
#checking Null Values
df.isnull().sum()

Unnamed: 0               0
id                       0
price                    0
owner                    0
collectionName           0
collectionTitle          0
img                   4685
title                    0
propertyCategory         0
creators                 0
attributes               0
properties               0
tokenDelegateValid       0
rarity                2174
version                  0
origin_attributes        0
Outfit                   0
Head                     0
Glasses                  0
Eyes                     0
Extras                   0
Skin                     0
Mouth                    0
Body                     0
Background               0
Face                     0
dtype: int64

In [5]:
#data selection
new_df = df[["price","Outfit","Head","Glasses","Eyes","Extras","Skin","Mouth","Body","Background","Face"]]
new_df.head()

,price,Outfit,Head,Glasses,Eyes,Extras,Skin,Mouth,Body,Background,Face
0,0.58,None,RedSidewaysCap,FlyEyeGlasses,Regular,None,None,None,Inverted,DarkBlue,None
1,0.60,RedSweaterVest,AfroBandana,None,Regular,None,None,Closed,BlackMonochrome,Green,None
2,0.60,WhiteBeaterJeans,RedDomeHat,FlyEyeGlasses,Regular,None,None,None,Base,Pink,None
3,0.60,BlackSuspenderSuit,TopHat,None,Regular,None,None,Closed,Base,Green,None
4,0.64,DoubleBreastedSuit,BlondeCurlyHair,None,Crosses,None,None,Closed,Base,Green,None

In [6]:
new_df.dtypes

price         float64
Outfit         object
Head           object
Glasses        object
Eyes           object
Extras         object
Skin           object
Mouth          object
Body           object
Background     object
Face           object
dtype: object

## Encoding Categorical Features

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
categorical_feature_cols = [
    'Outfit',
    'Head',
    'Glasses',
    'Eyes',
    'Extras',
    'Skin',
    'Mouth',
    'Body',
    'Background',
    'Face'
]

In [9]:
#Encode data
enc = OneHotEncoder(handle_unknown='ignore')

enc_df = pd.DataFrame(enc.fit_transform(new_df[categorical_feature_cols]).toarray())
enc_df.index = list(enc_df.index)

#add labels
enc_df.columns = enc.get_feature_names_out()

#merge and drop
dfp = new_df.reset_index(drop=True).merge(enc_df.reset_index(drop=True), left_index=True, right_index=True)
new_df = dfp.drop(columns=categorical_feature_cols)

new_df

,price,Outfit_80sWorkoutOutfit,Outfit_BabyBlueSuit,Outfit_BigGreySuit,Outfit_BlackMilitary,Outfit_BlackSuspenderSuit,Outfit_Blanket,Outfit_BlueMilitary,Outfit_BlueShirt,Outfit_BlueStripes,...,Background_Orange,Background_Pink,Background_Purple,Background_Red,Background_Silver,Background_Teal,Face_Beard,Face_Mask,Face_Mustache,Face_None
0,0.58,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.60,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6070,1250.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
6071,3500.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6072,7777.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6073,50000.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
6074,99999.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## Modeling

In [10]:
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, HuberRegressor, LassoCV, Lasso
from sklearn.metrics import confusion_matrix

In [11]:
features = [feature for feature in new_df.columns if '_' in feature]

In [12]:
X = new_df.loc[:,features]
y = new_df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Model Selection

In [13]:
from typing import List
def model_selection(models: List[dict], scores: List[str], X_train, y_train) -> dict:
    """Find the best model"""
    results = {}
    for candidate in models:
        model = GridSearchCV(
            candidate['constructor'], param_grid=candidate['param_grid'], scoring=scores
        )
        model.fit(X_train, y_train)
        mean_test_score = model.cv_results_['mean_test_score'].mean()
        results[candidate['name']] = mean_test_score
    print("The winner is: {}".format(
        max(results, key=results.get)
    ))
    return results

In [14]:
models = [
    {
        'name': 'Lasso',
        'constructor': Lasso(),
        'param_grid': {'alpha': [0.2, 0.4, 0.6, 0.8, 1.0]}
    },
    {
        'name': 'RandomForest',
        'constructor': RandomForestRegressor(random_state=0),
        'param_grid': {}
    },
    {
        'name': 'Huber',
        'constructor': HuberRegressor(),
        'param_grid': {'epsilon': [10], 'max_iter': [1000]}
    }
]
model_selection(models, 'neg_root_mean_squared_error', X_train, y_train)

The winner is: Huber

{'Lasso': -11143.924150943763,
 'RandomForest': -11612.710709964751,
 'Huber': -9438.539661388479}

## Stacking

In [15]:
from sklearn.ensemble import VotingRegressor

In [16]:
estimators = [('randomforest', RandomForestRegressor(random_state=42, n_estimators=200)),
              ('linear', LassoCV(random_state=42)),
              ('huber', HuberRegressor(epsilon=2, max_iter=1000))]

In [17]:
vreg = VotingRegressor(estimators)

In [18]:
cross_validate(vreg, X_train, y_train, cv=3,
               scoring=('neg_mean_squared_error'),
               return_train_score=True)

{'fit_time': array([17.89161658, 19.13145947, 18.99436831]),
 'score_time': array([0.16156769, 0.15313077, 0.1640799 ]),
 'test_score': array([-6.37782326e+06, -7.39690026e+08, -3.95504365e+07]),
 'train_score': array([-2.79251888e+08, -6.00746122e+06, -2.44090869e+08])}

In [19]:
vreg.fit(X_train, y_train)

VotingRegressor(estimators=[('randomforest',
                             RandomForestRegressor(n_estimators=200,
                                                   random_state=42)),
                            ('linear', LassoCV(random_state=42)),
                            ('huber',
                             HuberRegressor(epsilon=2, max_iter=1000))])

In [20]:
def predict(X, models):
    X = X
    y = np.empty(X.shape[0]) 
    y_pred= models.predict(X)
    return y

In [21]:
y_actual, y_pred = y_test, predict(X_test, vreg)

In [22]:
predict_df = pd.DataFrame({'Actual': y_actual, 'Predicted': y_pred, 'Error': y_pred-y_actual})
from sklearn import metrics
-metrics.mean_squared_error(y_test, y_pred)

-7529034.923668223

In [23]:
predict_df.sample(20)

      Actual      Predicted
2706    5.00  6.508161e-311
2902  500.00  4.156990e-311
339     1.20  6.020102e-311
4030    2.00  4.373433e-311
3518    1.00  3.282727e-311
4262    3.10  4.195186e-311
4760    0.49  1.167098e-312
5141    1.00  3.643467e-311
3967    1.69  3.227556e-311
2549    3.00  6.864656e-311
2094    1.40  6.410549e-311
3956    1.60  8.214246e-311
2387    2.00  7.475791e-311
4863    0.55  6.160154e-311
3708    1.20  6.896486e-312
1046    3.00  2.255682e-311
677     1.69  6.096494e-311
5033    0.90  6.465721e-311
2972    0.30  2.412709e-311
2254    1.69  6.830704e-311